### PR TITLE
Amazee Recipes

### PR DESCRIPTION
**Pull request by pmelab**
## Package(s) involved
New package: `@amazeelabs/recipes`

## Description of changes
Created a recipe-engine based on the [lit](https://github.com/vijithassar/lit) bash script. New recipes are written as markdown files with embedded Typescript code. The markdown files can be rendered into the `silverback-website` while they are also compiled to javascript and executable as a `amazee-recipes` tool that can be installed via `npm install -g @amazeelabs/recipes`.

## Motivation and context
Documentation that tests itself and provides automation at the same time. Inspired by Gatsby recipes but simpler.

## How has this been tested?
Recipes are executed during CI and test themselves.

## Review instructions
The most important part is `create-monorepo.ts.md`, which is the first self-testing recipe that sets up a monorepo. The `lit.sh` file does not have to be reviewed since its not my code.

Can be tested by running `yarn prepare && node ./dist/index.js` as long as it has not been published to npm.

### CODE REVIEW

**Review by marcotisi — APPROVED** [review]
Cool thing @pmelab! It works for me 👍

**Comment by Leksat** [comment]
For me it stops to work here:
```
alex@mbp ~/work/silverback-mono/packages/npm/@amazeelabs/recipes % node ./dist/index.js
✔ Pick a recipe › create-monorepo
2021-04-19 16:13:27.611  INFO verified git version
2021-04-19 16:13:27.625  INFO verified node version
2021-04-19 16:13:27.763  INFO verified yarn version
? Choose a project name: › somename
```
I can edit the name, but hitting `Enter` does nothing.

**Comment by Leksat** [comment]
Also, it gives me two options in the beginning: `create-monorepo` and `create-monorepo.js` - is there a difference?

**Comment by pmelab** [comment]
- [x] fixed the problem reported by @Leksat
- [x] less verbose syntax for executing bash commands
- [x] moved logging into helper functions
- [x] auto-prepend helpers import
- [x] write recipe-log into `RECIPES.md` to keep track of recipes executed within a project
- [ ] render recipes as Gatsby pages into `silverback-website`
- [ ] add Lerna to the `create-monorepo` recipe
- [ ] add a first additional recipe
- [ ] `README.md` with documentation for helper functions

**Comment by Leksat** [comment]
Looks great!

- `create-monorepo` works like a charm
- `add-drupal` and `add-gatsby` error (but I probably don't know how to use them?)

**Pull request merged**
