### PR TITLE
feat: extract gatsby theme from starter

### PR DESCRIPTION
**Pull request by marcotisi**
## Description

This PR:
- creates a basic `@amazeelabs/gatsby-amazee-theme`
- configures `tailwind` and `post-css` with the same plugins of https://github.com/AmazeeLabs/gatsby-starter-amazee
- removes the configuration for those packages from `silverback-website` and `gatsby-starter`
- uses the new theme in `silverback-website`
- adds `Header`, `Footer` and `SEO` components to `gatsby-theme-core` as long as `useSiteMetadata` hook and a `Layout`
- shadows `Footer` component in `silverback-website` to demonstrate how shadowing works.

## Motivation

We need to extract common plugins and settings from `gatsby-starter` and `silverback-website` into a new `gatsby-amazee-theme`

## Related issue

#95 

## Tested

No

## Notes

Please note that `tailwind.config.js` and `tailwind.css` are still scaffolded from `gatsby-starter` because those two files are always changed when creating a new website.

### CODE REVIEW

**Comment by marcotisi** [comment]
@pmelab @unamaria what do you think about the PR description? I think that it should give a good context to a reader who doesn't know the details and, if you like it, we could create a PR template inside this monorepo.

**Comment by pmelab** [comment]
> @pmelab @unamaria what do you think about the PR description? I think that it should give a good context to a reader who doesn't know the details and, if you like it, we could create a PR template inside this monorepo.

Yes, a PR template is a good idea. 👍

**Review by pmelab — CHANGES_REQUESTED** [review]
Should we rename the theme to `gatsby-theme`? In analogy to `gatsby-starter`? We don't need the `amazee` since its already in our namespace. Or perhaps `gatsby-theme-base` since there might be more?

And I think we should prototype the full workflow before merging this in to make sure everything works:

- [x] add a component to `silverback-theme` that is directly used in `silverback-website`
- [x] add a component to `silverback-theme` that is overridden in `silverback-website`
- [ ] integrate storybook for `silverback-theme` (directly in there? separate package?)
- [ ] integrate storybook for `silverback-website` (maybe look into [Storybook Composition](https://medium.com/storybookjs/storybook-composition-af0da9084fba)?)

**Comment by marcotisi** [comment]
Yes, sounds fine to me! I think that we could integrate Storybook in a separate PR, just to avoid having too many irons in the fire. What do you think?

**Review by pmelab — APPROVED** [review]

**Pull request merged**
