### PR TITLE
Gutenberg entity usage improvements

### PR DESCRIPTION
**Pull request by chindris**
## Package(s) involved

silverback_gutenberg

## Description of changes

Adds two entity usage plugins:
- one that tracks the linked content (coming from html link tags)
- one that tracks the referenced content from arbitrary gutenberg blocks, which have a uuid, and optionally an entityType, attribute. For example, if the project defines a custom/link-item block which has a gutenberg link control and stores the uuid and the entity type into the **uuid** and **entityType** attributes, them the plugin is able to track the usage of that content.

## Related Issue(s)

https://github.com/AmazeeLabs/silverback-mono/issues/1382

## How has this been tested?

- [x] Kernel tests
- [x] Unit tests

### CODE REVIEW

**Review by Leksat — APPROVED** [review]
Tested on `silverback-template`. Works great! But only for nodes.

For media we need to investigate more. This is what I saw in the database when tried to link a node and a media:
```html
<!-- wp:paragraph -->
<p>a link to <a href="/node/6c0ac38d-ab7d-452d-b4d2-a98814fde715" data-type="Content: Basic page" data-id="6c0ac38d-ab7d-452d-b4d2-a98814fde715" data-entity-type="node">page</a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>a link to <a href="/media/5" data-type="Media: Document" data-id="0d00d8a2-65eb-4496-8e36-294e18b044ec">media</a></p>
<!-- /wp:paragraph -->
```

For media:
- `href` is not transformed to uuid - can cause issues with content export
- `data-entity-type` is missing - probably that's why it's not tracked

Could you take a look at the media? Maybe it's easy to fix. Or let's merge this one and create follow-ups for media.

**Comment by chindris** [comment]
Hi @Leksat !

I fixed the media issue with the last commit: https://github.com/AmazeeLabs/silverback-mono/pull/1389/commits/52b1a5c52ea25f7164efe17bb098ca00e3858870 (when you test on silverback-template, make sure to just resave the Media matcher config, from the Linkit profile).

**Review by Leksat — APPROVED** [review]
@chindris I won't test it manually this time. The changes look good! Let's merge and enable it in the template?

**Comment by chindris** [comment]
Hi @Leksat !
PR merged, this can be tested now in the template.

**Pull request merged**
