### PR TITLE
feat(gatsby): graphql fields for fetching entity revisions

### PR DESCRIPTION
**Pull request by pmelab**
## Package(s) involved

`amazeelabs/silverback_gatsby`

## Description of changes

Add `load[Type]Revision` root level fields to retrieve specific revisions of an entity

## Motivation and context

Can be used to display specific revisions when loading them in the browser for preview purposes.

## Related Issue(s)

#1060 

## How has this been tested?

Kerneltests

### CODE REVIEW

**Review by Leksat — APPROVED** [review]
Looks good!

How would client fetch the list of available revisions?

**Review by colorfield — APPROVED** [review]

**Comment by colorfield** [comment]
@Leksat this PR will unblock the implementation of the last revision tab in https://github.com/AmazeeLabs/silverback-mono/issues/1062, we could perhaps create a follow-up for the list of available revisions?

**Comment by pmelab** [comment]
@Leksat listing all revisions is not a requirement at the moment. we need this so Drupal can trigger preview of one specific revision (e.g. from Drupals revision list).

**Comment by Leksat** [comment]
Ah! So it will be something like `/page-template?id=123&revision=12345` path?

**Comment by pmelab** [comment]
@Leksat precisely

**Pull request merged**
